In [3]:
import torch
import numpy as np

In [5]:
y = torch.empty(2, 2)
x = torch.ones(2, 2, dtype=torch.float64)
z = torch.tensor([2.5, 0.1])
print(x.size())
print(x.dtype)
print(z)

torch.Size([2, 2])
torch.float64
tensor([2.5000, 0.1000])


In [6]:
# create two tensors of random values
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.5299, 0.6283],
        [0.0881, 0.6827]])
tensor([[0.0866, 0.8910],
        [0.7141, 0.2474]])


In [7]:
# these both are the same
z = x + y
z = torch.add(x, y)
z = torch.sub(x, y)
z = x * y
print(z)

tensor([[0.0459, 0.5598],
        [0.0629, 0.1689]])


In [8]:
x = torch.rand(5, 3)
print(x[:, 1])
print(x[1, 1].item())

tensor([0.2586, 0.5077, 0.1952, 0.2341, 0.1616])
0.5076724290847778


In [9]:
x = torch.rand(4, 4)
print(x)
# reshape into different dimension, -1 will infer
y = x.view(8, -1)
print(y)
print(y.size())

tensor([[0.6623, 0.4771, 0.0654, 0.0994],
        [0.0048, 0.4196, 0.9810, 0.2868],
        [0.8094, 0.5075, 0.4875, 0.1556],
        [0.1190, 0.9842, 0.8954, 0.5550]])
tensor([[0.6623, 0.4771],
        [0.0654, 0.0994],
        [0.0048, 0.4196],
        [0.9810, 0.2868],
        [0.8094, 0.5075],
        [0.4875, 0.1556],
        [0.1190, 0.9842],
        [0.8954, 0.5550]])
torch.Size([8, 2])


In [10]:
# convert numpy to torch tensor, the memory are shared
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [11]:
# opposite operation, memory is shared. If tensor is on GPU
a = np.ones(5)
b = torch.from_numpy(a)

a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
# Check for apple multi process service (apple metal)
print(torch.has_mps)
# set device to mps if available
torch.device = "mps"

True


In [23]:
x = torch.ones(5, device="mps")
y = torch.ones(5, device="mps")
# operation performed on GPU which is must faster
z = x + y

In [ ]:
# Numpy will have errors since it only deals with CPU tensors!!!
# you cannot convert a GPU tensor back to numpy

z = z.to("cpu") # back to cpu

# alot of times when a tensor is created, then you see the argument
# requires_grad=True, this means that it will later calculate the gradience
# which means you want to optimize